### ISSUE TITLE
Add .ics file on booking

### ISSUE THREAD

**Issue by almonk** [withassociates/with-pair#44]
Hiii

I want to be able to download an ics file for my Google calendar when I book a session.

That'd be hot.

Alx

**Comment by jgwhite** [comment]
@calumgunn didn’t you implement exactly this recently?

**Comment by calumgunn** [comment]
@jgwhite Think I can do pretty easily with this: http://www.addthisevent.com

**Comment by jgwhite** [comment]
@calumgunn :shipit:

**Comment by almonk** [comment]
YOU GUYS :tada:
